[package]
name = "dlua"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
logos = "0.15.1"
rayon = "1.11.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
walkdir = "2.5.0"
